### ISSUE TITLE
Wrong Steps I think

### ISSUE THREAD

**Issue by Entreri86** [MicrosoftDocs/dynamics365smb-devitpro-pb#1940]
The compatibility matrix specifies that BC14 Spring 2019 can be upgraded to BC18.0 (2021 release wave 1).

In task 7 it specifies that the BC14 Administration Shell should be used to publish the Microsoft extensions "Microsoft_System Application.app", "Microsoft_Base Application.app" and "Microsoft_Application.app", the latter introduced in version 15.3.

When I try to publish the 18.0 extensions from the 14.0 shell it fails as normal. If I publish from the Shell of 18.0 it gives an error in the command "Start-NAVDataUpgrade -ServerInstance <server instance name> -Tenant <tenant ID> -FunctionExecutionMode Serial -SkipAppVersionCheck" of task 10 because the table of "Permission Set" is missing the 4 fields of "System Created At", "System created By", "System modified by" and "System modifiedAt".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05a03500-5e14-08ad-8fe0-f1bd752312b9
* Version Independent ID: 543729ab-ec13-3e2a-dc1d-73a9567b9802
* Content: [Upgrading Unmodified C/AL Application to Version 18 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v14-v18)
* Content Source: [dev-itpro/upgrade/upgrade-unmodified-application-v14-v18.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-unmodified-application-v14-v18.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback!

There's an error in Task 7 of the article. You should use the version 18.0 Admin shell. 

I'm not sure what's causing the error you're getting on Start-NAVDataUpgrade. I just tried this scenario, following the steps in the article, and it succeeded. Can you tell me what version of 14 and 18 you're working with?

**Comment by Entreri86** [comment]
Hello!,

Thank you for answering so quickly! I give you the details:

1. Upgrade Dynamics Nav 2016 CU14 to BC 14 CU03
2. Upgrade BC 14 CU03 to BC18.0
3. Task 5.3 Set-NavServerConfiguration -ServerInstance <BC18 server instance> -KeyName "UsePermissionSetsFromExtensions" -KeyValue false
4. Attached event viewer error.

If in that step you use the "UsePermissionSetsFromExtensions" = true everything works correctly.


`ProcessId: 11016
Tag: 00001WB
ThreadId: 33
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: </Message><Level>Error</Level><Task></Task><Opcode>Información</Opcode><Channel></Channel><Provider></Provider><Keywords><Keyword>Clásico</Keyword></Keywords></RenderingInfo></Event><Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='MicrosoftDynamicsNavServer$BC180_0'/><EventID Qualifiers='0'>701</EventID><Level>2</Level><Task>33</Task><Keywords>0x80000000000000</Keywords><TimeCreated SystemTime='2021-06-28T09:38:03.385634200Z'/><EventRecordID>30442895</EventRecordID><Channel>Application</Channel><Computer>CORE-SSD.ekamat.es</Computer><Security/></System><EventData><Data>Server instance: BC180_0
Category: Sql
ClientSessionId: e46511e8-052e-4e37-a31a-aaeac0a0c06e
ClientActivityId: 332288f8-0eab-40b8-9300-92b6ecbebe86
ServerSessionUniqueId: 4e90c3a3-dfae-4a00-9040-faf5c4f23137
ServerActivityId: 4bafde4e-0db9-4ff8-96e5-5496d5dacea5
EventTime: 06/28/2021 09:38:03
Message (NavSqlException): This message had personal data removed. The original may still be in transient telemetry. Find it using the transientTelemetryId.
Exception happened during execution of a threshold action.
  Exception type: NavSqlException,
  Threshold tag: 000007L,
  Execution time over threshold: False,
  Execution time: 91 ms,
  Threshold: 750 ms
  Message: Long running SQL statement
  Task ID: 3
  Connection ID: 4
  SQL server session ID: 63
  Client Type: Background
  Database Server Name: CORE-SSD\SQL2017
  Database Name: BC(18-0)
  Current Company Name: 
  Statement: SELECT "2000000004"."timestamp","2000000004"."Role ID","2000000004"."Name","2000000004"."Hash","2000000004"."$systemId","2000000004"."$systemCreatedAt","2000000004"."$systemCreatedBy","2000000004"."$systemModifiedAt","2000000004"."$systemModifiedBy" FROM "SQLDATABASE".dbo."Permission Set" "2000000004"  WITH(READUNCOMMITTED)  WHERE ("2000000004"."Role ID"=@0)
    AppObjectType: CodeUnit
  AppObjectId: 104030
  AL CallStack: "Upgrade Plan Permissions"(CodeUnit 104030).TryInsertPermissionSet line 10 - Base Application by Microsoft
"Upgrade Plan Permissions"(CodeUnit 104030).AddBackupRestorePermissionSet line 5 - Base Application by Microsoft
"Upgrade Plan Permissions"(CodeUnit 104030).SetBackupRestorePermissions line 8 - Base Application by Microsoft
"Upgrade Plan Permissions"(CodeUnit 104030).OnUpgradePerDatabase line 2 - Base Application by Microsoft
"Upgrade Triggers"(CodeUnit 2000000008).OnUpgradePerDatabase line 2

ParentException: NavSqlException
Message not shown because the NavBaseException(string, Exception, bool) constructor was used.
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ThrowNavSqlException(SqlExceptionAdapter exceptionAdapter, Boolean transactionNoLongerValid, String commandText, Boolean isLastExceptionARollbackCause, Boolean logExceptions, NavCancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.MapException(SqlExceptionAdapter exceptionAdapter, String commandText, Boolean isRollbackAction, Nullable`1 timeout, NavCancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.&lt;&gt;c__DisplayClass130_0`1.&lt;ExecuteFunction&gt;b__0()
   at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ExecuteFunctionWithTrace[T](EventTask task, Func`1 function, String commandText, SqlCommand sqlCommand, Boolean isAdoCommand, NavCancellationToken cancellationToken)
InnerException:
RootException: SqlException
El nombre de columna '$systemCreatedAt' no es válido.
El nombre de columna '$systemCreatedBy' no es válido.
El nombre de columna '$systemModifiedAt' no es válido.
El nombre de columna '$systemModifiedBy' no es válido.
No se puede preparar la instrucción o instrucciones.
ExceptionStackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&amp; dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task&amp; task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task&amp; task, Boolean&amp; usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlCommand.&lt;ExecuteReader&gt;b__63_0()
   at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.&lt;&gt;c__DisplayClass130_0`1.&lt;ExecuteFunction&gt;b__0()
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.FailedSqlOperationExceptionFilter(Exception e, EventTask task, String commandText, Int64 startMilliSeconds, Boolean&amp; recursionDetected)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ExecuteFunctionWithTrace[T](EventTask task, Func`1 function, String commandText, SqlCommand sqlCommand, Boolean isAdoCommand, NavCancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ThrowNavSqlException(SqlExceptionAdapter exceptionAdapter, Boolean transactionNoLongerValid, String commandText, Boolean isLastExceptionARollbackCause, Boolean logExceptions, NavCancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.MapException(SqlExceptionAdapter exceptionAdapter, String commandText, Boolean isRollbackAction, Nullable`1 timeout, NavCancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.&lt;&gt;c__DisplayClass130_0`1.&lt;ExecuteFunction&gt;b__0()
   at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ExecuteFunctionWithTrace[T](EventTask task, Func`1 function, String commandText, SqlCommand sqlCommand, Boolean isAdoCommand, NavCancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlCommand.ExecuteReader(NavCancellationToken cancellationToken)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlIsamQueryCommand.ExecuteFindEqualCommand(FilterExpression filter, NavDatabase database, Int32 companyIndex, Nullable`1 companyId)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlIsamQueryCommand.&lt;&gt;c__DisplayClass40_0.&lt;InternalFindEqual&gt;b__1(NavSqlCommand command)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ExecuteCommandAndCacheOnSuccess[T](NavSqlCommandCacheKey commandKey, Func`1 newCommandFunc, Func`2 executeFunc)
   at Microsoft.Dynamics.Nav.Runtime.NavSqlIsamQueryCommand.InternalFindEqual(NavDatabase database, DataProviderRequest request)
   at Microsoft.Dynamics.Nav.Runtime.SqlTableDataProvider.TryGetOnUniqueId(DataProviderRequest request, ReadOnlyRecordBuffer&amp; recordBuffer)
   at Microsoft.Dynamics.Nav.Runtime.DataAccess.InternalTryGetByPrimaryKey(PrimaryKeyCacheRequest request, MutableRecordBuffer&amp; recordBuffer)
   at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.InternalFindRecordWithoutCheckingValues(DataError errorLevel, PrimaryKeyCacheRequest request, Boolean useRecord, Boolean calcAutoCalcFields)
   at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.GetRecord(DataError errorLevel, NavValue[] values)
   at Microsoft.Dynamics.Nav.Runtime.NavRecord.ALGet(DataError errorLevel, NavValue[] values)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit104030.TryInsertPermissionSet_Scope__802109793.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit104030.TryInsertPermissionSet(NavCode permissionSetID, NavText permissionSetName)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit104030.AddBackupRestorePermissionSet_Scope_1286930995.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit104030.AddBackupRestorePermissionSet()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit104030.SetBackupRestorePermissions_Scope_2121045765.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit104030.SetBackupRestorePermissions()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit104030.OnUpgradePerDatabase_Scope.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit104030.OnUpgradePerDatabase()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit104030.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.EventSubscription.NavEventScope.CallEventSubscriberInternal(NavEventSubscription subscriber, NavApplicationObjectBase subscriberInstance, Object[] parameters)
   at Microsoft.Dynamics.Nav.EventSubscription.NavEventScope.CallEventSubscriber(NavApplicationObjectBase callingApplicationObject, NavEventSubscription subscriber, NavApplicationObjectBase subscriberInstance, Object[] parameters)
   at Microsoft.Dynamics.Nav.EventSubscription.NavEventScope.ProcessCallToTypeAndManualSubscriptions(NavApplicationObjectBase callerApplicationObject, NavEventSubscription[] subscriptions, PrepareParametersCallBack prepareParameters)
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.RunEvent()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2000000008.OnUpgradePerDatabase()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2000000008.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.Runtime.NavSystemCodeunit.Invoke(Int32 methodId, Object[] arguments)
   at Microsoft.Dynamics.Nav.Runtime.SessionTransactionManager.TransactionScope(Action code)
   at Microsoft.Dynamics.Nav.Runtime.NavSystemCodeunitUpgradeTriggers.InvokeUpgradeEvent(NavUpgradeEvent upgradeEvent)
   at Microsoft.Dynamics.Nav.Runtime.RetryManager.&lt;&gt;c__DisplayClass11_0.&lt;PerformOperationWithRetries&gt;b__0()
   at Microsoft.Dynamics.Nav.Runtime.RetryManager.PerformOperationWithRetries[T](Func`1 operation, Action resetAction, String operationName)
   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppUpgradeManager.RaisePerDatabaseUpgradeEvent(NavUpgradeEvent upgradeEvent)
   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppUpgradeManager.SetupSessionAndExecuteAction(NavSession upgradeSession, Action`1 sessionAction, Boolean setupDebugging)
   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppOperationProcessor`1.RunActionInSession(Boolean runInNewSystemSession, Action`1 sessionAction, LanguageSetting language, Boolean enableDebugging)
   at Microsoft.Dynamics.Nav.Runtime.Apps.NavAppUpgradeManager.RunNavAppUpgradeEvent(String companyName, Boolean runInSystemSession, NavUpgradeEvent upgradeEvent)
   at Microsoft.Dynamics.Nav.Runtime.ExecuteNavEventActivity.NavExecute(NativeActivityContext context, NavSession session)
   at Microsoft.Dynamics.Nav.Runtime.NavWorkflowTenantSessionManager.Microsoft.Dynamics.Nav.Runtime.INavWorkflowTenantSessionManager.RunActionInSystemSession(Action`1 action)
   at Microsoft.Dynamics.Nav.Runtime.Workflow.NavBaseActivity.Execute(NativeActivityContext context)
   at System.Activities.NativeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager)
   at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)
   at System.Activities.Runtime.ActivityExecutor.TryExecuteNonEmptyWorkItem(WorkItem workItem)
   at System.Activities.Runtime.ActivityExecutor.OnExecuteWorkItem(WorkItem workItem)
   at System.Activities.Runtime.Scheduler.Callbacks.ExecuteWorkItem(WorkItem workItem)
   at System.Activities.Runtime.Scheduler.OnScheduledWork(Object state)
   at System.Runtime.Fx.SendOrPostThunk.UnhandledExceptionFrame(Object state)
   at System.Runtime.IOThreadScheduler.ScheduledOverlapped.IOCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Runtime.Fx.IOCompletionThunk.UnhandledExceptionFrame(UInt32 error, UInt32 bytesRead, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)`

**Comment by jswymer** [comment]
Hello, I spoke with the dev team, and this is a bug, which they've fixed. The fix is either in 18.2, which is out now, https://support.microsoft.com/en-us/topic/update-18-2-for-microsoft-dynamics-365-business-central-2021-release-wave-1-application-build-18-2-26490-platform-build-18-0-26464-358d71d0-29b2-4b82-aa62-f0601161ceff
or the upcoming 18.3. I'm looking for verification.

**Comment by Entreri86** [comment]
Thanks!

Could you (since we are) add a note or something in the documentation of the technical upgrade steps so that another person who performs these steps does not lose their minds? (I lost almost 10 hours ...)

**Comment by jswymer** [comment]
Hello, we've added an issue about this to our [Known Issues](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/known-issues) article. The update has not yet been published, but it will be soon. Thanks for the feedback!
