### ISSUE TITLE
"Invoke" is not a valid function name

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/dynamics365smb-devitpro-pb#1959]
Please add a note that explains that the name `Invoke` is not valid as a procedure name when it is published as an unbound action. 

If you are trying to call a procedure called `Invoke` as an unbound action you receive the error "Ambiguous match found", which is not that informative. I assume that this is a reflection issue, where the .NET assembly created from AL already contains other functions with the name `Invoke`...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc701118-4d83-4d5a-efcc-420fb870300f
* Version Independent ID: 10a28599-afa8-a4e9-0d9a-b80749421de2
* Content: [Creating and Interacting with an OData V4 Unbound Action - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-unbound-action)
* Content Source: [dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-unbound-action.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-creating-and-interacting-with-odatav4-unbound-action.md)
* Service: **dynamics365-business-central**
* GitHub Login: @ap3rus
* Microsoft Alias: **vlnagorn**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. Can you elaborate on this, the topic this is filed on does not contain a procedure named Invoke? I am not sure that we can add notes for (all) ambiguous names. Thanks.

**Comment by jwikman** [comment]
Hi,

I'm not 100% sure on how this is done, but at least I know that if I publish a procedure named `Invoke` as an unbound action, I get below error in the event log, and the call failed with an "Ambiguous match found." error.

```
This version of Server instance: BC
Tenant ID: 
Environment Name: 
Environment Type: 
Type: System.Reflection.AmbiguousMatchException
Message: Ambiguous match found.
StackTrace:
     at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
     at System.Type.GetMethod(String name)
     at Microsoft.Dynamics.Nav.Service.OData.V4.CodeunitInvocationHelper.Invoke(NavSession session, NavODataCodeunitFunctionAnnotation codeunitFunctionAnnotation, ODataActionParameters values)
     at Microsoft.Dynamics.Nav.Service.OData.V4.GenericODataController.<>c__DisplayClass14_1.<InvokeUnboundAction>b__1(NavSession session)
     at Microsoft.Dynamics.Nav.Service.OData.NavServiceBase.Execute[TResult](HttpRequestMessage request, NavSession session, Func`2 operation, String companyName, Boolean isCompanyContext)
     at Microsoft.Dynamics.Nav.Service.OData.NavServiceBase.Execute[TResult](String companyName, Func`2 operation)
     at Microsoft.Dynamics.Nav.Service.OData.V4.GenericODataController.<>c__DisplayClass14_0.<InvokeUnboundAction>g__InvokeUnboundActionOperation|0(PartnerDiagnosticsWebServiceCallTraceBuilder traceBuilder, NavCancellationToken cancellationToken)
     at Microsoft.Dynamics.Nav.Service.OData.V4.GenericODataController.Run[T](String diagnosticsTag, Func`3 func, CancellationToken requestToken, HttpStatusCode defaultResponse, String callerMethodName)
     at Microsoft.Dynamics.Nav.Service.OData.V4.GenericODataController.InvokeUnboundAction(ODataActionParameters parameters, CancellationToken requestToken)
     at lambda_method(Closure , Object , Object[] )
     at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
     at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
Source: mscorlib
HResult: -2147475171
StackTrace:
     at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
     at System.Type.GetMethod(String name)
     at Microsoft.Dynamics.Nav.Service.OData.V4.CodeunitInvocationHelper.Invoke(NavSession session, NavODataCodeunitFunctionAnnotation codeunitFunctionAnnotation, ODataActionParameters values)
     at Microsoft.Dynamics.Nav.Service.OData.V4.GenericODataController.<>c__DisplayClass14_1.<InvokeUnboundAction>b__1(NavSession session)
     at Microsoft.Dynamics.Nav.Service.OData.NavServiceBase.Execute[TResult](HttpRequestMessage request, NavSession session, Func`2 operation, String companyName, Boolean isCompanyContext)
     at Microsoft.Dynamics.Nav.Service.OData.NavServiceBase.Execute[TResult](String companyName, Func`2 operation)
     at Microsoft.Dynamics.Nav.Service.OData.V4.GenericODataController.<>c__DisplayClass14_0.<InvokeUnboundAction>g__InvokeUnboundActionOperation|0(PartnerDiagnosticsWebServiceCallTraceBuilder traceBuilder, NavCancellationToken cancellationToken)
     at Microsoft.Dynamics.Nav.Service.OData.V4.GenericODataController.Run[T](String diagnosticsTag, Func`3 func, CancellationToken requestToken, HttpStatusCode defaultResponse, String callerMethodName)
     at Microsoft.Dynamics.Nav.Service.OData.V4.GenericODataController.InvokeUnboundAction(ODataActionParameters parameters, CancellationToken requestToken)
     at lambda_method(Closure , Object , Object[] )
     at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
     at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
```

`Invoke` function names seems to be used a lot internally in the BC runtime, so my conclusion of above stack trace is that the system fails to find my function `Invoke`, because there are also other functions with the same name.

So either it's a bug (and should be fixed) or a feature (and should be documented). 🙂

I spent quite some time finding this out, so it would make sense to help others avoid spending the same time. Please let me know if you think this should be reported as a bug to MS Support instead.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the elaborate reply. Having discussed this internally, we have opened a bug to fix this. This means that it will be on our backlog and prioritized accordingly. Thanks for your patience in advance. I will close this issue for now on the docs.
