### ISSUE TITLE
"Developing a Custom API" example code puts the subpage part inside the repeater, but that is invalid

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#2393]
It has this:

```al
page 50100 "API Car Brand"
{
    PageType = API;

    APIVersion = 'v1.0';
    APIPublisher = 'bctech';
    APIGroup = 'demo';

    EntityCaption = 'CarBrand';
    EntitySetCaption = 'CarBrands';
    EntityName = 'carBrand';
    EntitySetName = 'carBrands';

    ODataKeyFields = SystemId;
    SourceTable = "Car Brand";

    Extensible = false;
    DelayedInsert = true;

    layout
    {
        area(content)
        {
            repeater(Group)
            {
                field(id; Rec.SystemId)
                {
                    Caption = 'Id';
                    Editable = false;
                }

                field(name; Rec.Name)
                {
                    Caption = 'Name';
                }
                field(description; Rec.Description)
                {
                    Caption = 'Description';
                }
                field(country; Rec.Country)
                {
                    Caption = 'Country';
                }
                part(carModels; "API Car Model")
                {
                    Caption = 'Car Models';
                    EntityName = 'carModel';
                    EntitySetName = 'carModels';
                    SubPageLink = "Brand Id" = Field(SystemId);
                }
            }
        }
    }
}
```

but that crashes when run from the Web Client:

```none
Error accessing Website BC
Type: Microsoft.Dynamics.Framework.UI.LogicalControlCloneException
Message: Repeater cannot clone control for type: Microsoft.Dynamics.Framework.UI.FormHostControl because it does not implement the IRepeatable interface or the interface implementation returns a control type that is not valid.
Source: Microsoft.Dynamics.Framework.UI
HResult: -2146233088
StackTrace:
     at Microsoft.Dynamics.Framework.UI.LogicalControl.Clone(Boolean templateControlWillBeAssigned) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\LogicalControl.cs:line 3355
     at Microsoft.Dynamics.Framework.UI.RepeaterViewportControl.CloneControlAndChildren(RepeaterRowControl rowWhereCloneWillBeAdded, LogicalControl controlToClone) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterViewPortControl.cs:line 1155
     at Microsoft.Dynamics.Framework.UI.RepeaterViewportControl.CloneRowTemplateChildren(RepeaterRowControl row) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterViewPortControl.cs:line 1145
     at Microsoft.Dynamics.Framework.UI.RepeaterViewportControl.CreateRow() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterViewPortControl.cs:line 1138
     at Microsoft.Dynamics.Framework.UI.RepeaterViewportControl.AddRow(RowEntry rowEntry) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterViewPortControl.cs:line 1114
     at Microsoft.Dynamics.Framework.UI.RepeaterCurrentRowViewportControl.UpdateViewport(BindingManager bindingManager) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterCurrentRowViewPortControl.cs:line 116
     at Microsoft.Dynamics.Framework.UI.RepeaterCurrentRowViewportControl.Initialize(BindingManager bindingManager) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterCurrentRowViewPortControl.cs:line 71
     at Microsoft.Dynamics.Framework.UI.RepeaterControl.AddViewport(RepeaterViewportControl viewport) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterControl.cs:line 940
     at Microsoft.Dynamics.Framework.UI.RepeaterControl.CreateCurrentRowViewport() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterControl.cs:line 1270
     at Microsoft.Dynamics.Framework.UI.RepeaterControl.get_DefaultViewport() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterControl.cs:line 824
     at Microsoft.Dynamics.Framework.UI.RepeaterControl.get_CurrentRowInViewportHandler() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterControl.cs:line 1795
     at Microsoft.Dynamics.Framework.UI.RepeaterControl.EnsureCurrentRowInViewport() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterControl.cs:line 1710
     at Microsoft.Dynamics.Framework.UI.RepeaterRenderPreparationStrategy.EnsureCurrentRowInViewport(RepeaterControl repeaterControl) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterRenderPreparationStrategy.cs:line 55
     at Microsoft.Dynamics.Framework.UI.RepeaterRenderPreparationStrategy.Prepare(RepeaterControl repeaterControl) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterRenderPreparationStrategy.cs:line 39
     at Microsoft.Dynamics.Framework.UI.RepeaterInteractionInvokedHandler.OnInteractionInvoked(Object sender, LogicalInteractionInvocationEventArgs e) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\RepeaterInteractionInvokedHandler.cs:line 49
     at Microsoft.Dynamics.Framework.UI.InteractionNotifier.NotifyInteractionInvoked(LogicalInteractionInvocationResultEventArgs eventArgs) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionNotifier.cs:line 72
     at Microsoft.Dynamics.Framework.UI.InteractionInvoker.InvokeCore[T](String interactionName, Action`1 invokeMethod, T input) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionInvoker.cs:line 57
     at Microsoft.Dynamics.Framework.UI.InteractionInvoker.Invoke[T](String interactionName, Action`1 invokeMethod, T input) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionInvoker.cs:line 35
     at Microsoft.Dynamics.Framework.UI.LogicalInteraction`1.Invoke(T logicalInteractionInput) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\LogicalInteraction.cs:line 42
     at Microsoft.Dynamics.Framework.UI.Client.OpenFormExecutionStrategy.Execute() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Client\Interactions\ExecutionStrategies\OpenFormExecutionStrategy.cs:line 63
     at Microsoft.Dynamics.Framework.UI.InteractionManager.<>c__DisplayClass8_2.<InvokeInteractions>b__4() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionManager.cs:line 145
StackTrace:
     at Microsoft.Dynamics.Framework.UI.LogicalControl.Clone(Boolean templateControlWillBeAssigned) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\LogicalControl.cs:line 3355
     at Microsoft.Dynamics.Framework.UI.RepeaterViewportControl.CloneControlAndChildren(RepeaterRowControl rowWhereCloneWillBeAdded, LogicalControl controlToClone) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterViewPortControl.cs:line 1155
     at Microsoft.Dynamics.Framework.UI.RepeaterViewportControl.CloneRowTemplateChildren(RepeaterRowControl row) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterViewPortControl.cs:line 1145
     at Microsoft.Dynamics.Framework.UI.RepeaterViewportControl.CreateRow() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterViewPortControl.cs:line 1138
     at Microsoft.Dynamics.Framework.UI.RepeaterViewportControl.AddRow(RowEntry rowEntry) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterViewPortControl.cs:line 1114
     at Microsoft.Dynamics.Framework.UI.RepeaterCurrentRowViewportControl.UpdateViewport(BindingManager bindingManager) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterCurrentRowViewPortControl.cs:line 116
     at Microsoft.Dynamics.Framework.UI.RepeaterCurrentRowViewportControl.Initialize(BindingManager bindingManager) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterCurrentRowViewPortControl.cs:line 71
     at Microsoft.Dynamics.Framework.UI.RepeaterControl.AddViewport(RepeaterViewportControl viewport) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterControl.cs:line 940
     at Microsoft.Dynamics.Framework.UI.RepeaterControl.CreateCurrentRowViewport() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterControl.cs:line 1270
     at Microsoft.Dynamics.Framework.UI.RepeaterControl.get_DefaultViewport() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterControl.cs:line 824
     at Microsoft.Dynamics.Framework.UI.RepeaterControl.get_CurrentRowInViewportHandler() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterControl.cs:line 1795
     at Microsoft.Dynamics.Framework.UI.RepeaterControl.EnsureCurrentRowInViewport() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterControl.cs:line 1710
     at Microsoft.Dynamics.Framework.UI.RepeaterRenderPreparationStrategy.EnsureCurrentRowInViewport(RepeaterControl repeaterControl) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterRenderPreparationStrategy.cs:line 55
     at Microsoft.Dynamics.Framework.UI.RepeaterRenderPreparationStrategy.Prepare(RepeaterControl repeaterControl) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Forms\Repeater\RepeaterRenderPreparationStrategy.cs:line 39
     at Microsoft.Dynamics.Framework.UI.RepeaterInteractionInvokedHandler.OnInteractionInvoked(Object sender, LogicalInteractionInvocationEventArgs e) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\RepeaterInteractionInvokedHandler.cs:line 49
     at Microsoft.Dynamics.Framework.UI.InteractionNotifier.NotifyInteractionInvoked(LogicalInteractionInvocationResultEventArgs eventArgs) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionNotifier.cs:line 72
     at Microsoft.Dynamics.Framework.UI.InteractionInvoker.InvokeCore[T](String interactionName, Action`1 invokeMethod, T input) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionInvoker.cs:line 57
     at Microsoft.Dynamics.Framework.UI.InteractionInvoker.Invoke[T](String interactionName, Action`1 invokeMethod, T input) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionInvoker.cs:line 35
     at Microsoft.Dynamics.Framework.UI.LogicalInteraction`1.Invoke(T logicalInteractionInput) in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\LogicalInteraction.cs:line 42
     at Microsoft.Dynamics.Framework.UI.Client.OpenFormExecutionStrategy.Execute() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Client\Interactions\ExecutionStrategies\OpenFormExecutionStrategy.cs:line 63
     at Microsoft.Dynamics.Framework.UI.InteractionManager.<>c__DisplayClass8_2.<InvokeInteractions>b__4() in s:\repo\src\Platform\Client\Shared\Prod.ClientFwk\Interactions\InteractionManager.cs:line 145
```

IS it not the case that, as on any normal page, the `part` should be outwith the `repeater`, not inside it?

We have other API pages built with the `part` outwith the `repeater`, and they work - both programmatically, and to 'preview' using the Client, which we should retain the ability to do.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73d19576-22d5-b44d-0cc0-3a612f7a5a23
* Version Independent ID: aabda29a-5a84-d72e-945f-56b6cb9ba6cc
* Content: [Developing a custom API - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-custom-api#creating-api-pages)
* Content Source: [dev-itpro/developer/devenv-develop-custom-api.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-develop-custom-api.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - you are right, that is invalid syntax. We will update this example for the next doc refresh.
