### ISSUE TITLE
Error starting service - Task 2 Step 7 Connect a Microsoft Dynamics NAV 2018 Server instance to the converted database.

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#41]
This is NAV 2018 CU05 (21836)
I see this warning in the Application event log when starting the service for Task 2, Step 7.  Did I miss a step?
Server instance: InternalUPG
Tenant ID: 
<ii>User: 
Type: Microsoft.Dynamics.Nav.Types.NavMetadataNotFoundException
SuppressMessage: False
ContainsPersonalOrRestrictedInformation: False
DiagnosticsSuppress: True
MessageWithoutPrivateInformation: The metadata object Page 8615 was not found.
SuppressExceptionCreatedEvent: False
FatalityScope: None
Message: <ii>The metadata object Page 8615 was not found.</ii>
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddTenant(NavTenantMountingParameters mountingParameters)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.MountDefaultTenant(String databaseServerName, String databaseName, String databaseUserName, ProtectedDatabasePassword databasePassword, EncryptionProvider encryptionProvider, AzureKeyVaultSettings azureKeyVaultSettings, Boolean verifyServerInstanceKey)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSingleLegacyTenant(String databaseServerName, String databaseName, String databaseUserName, ProtectedDatabasePassword databasePassword, EncryptionProvider encryptionProvider, AzureKeyVaultSettings azureKeyVaultSettings)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.ConfigureTenants(ServerUserSettings settings, String encryptionKey)
     at Microsoft.Dynamics.Nav.Runtime.NavTaskFactory.<>c__DisplayClass11_0.<StartNewTask>b__0()
     at System.Threading.Tasks.Task.Execute()
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233088
</ii>

The next message in the event viewer is:
Server instance: InternalUPG
<ii>The service is shutting down.</ii>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 221f01d5-21a5-b244-e419-f83ed74f84eb
* Version Independent ID: 3327eb70-9edb-cd5b-e935-ccb5c3008d7f
* Content: [Converting a Database - Technical Upgrade - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/converting-a-database)
* Content Source: [dynamics-nav/Converting-a-Database.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Converting-a-Database.md)
* Service: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by GreatScott000** [comment]
Compile page 8615, attempt to start service again, same error except for Page 30 this time.

**Comment by GreatScott000** [comment]
Next is Page 31

**Comment by GreatScott000** [comment]
Page 50

So what is the problem, the documentation or is this an executable problem.
None of these objects objects are modified.

**Comment by GreatScott000** [comment]
So I gave up and went in and compiled all non-Table objects.  No I get the same error on Table 27.

**Comment by GreatScott000** [comment]
The database is a NAV 2017 RTM (which had be upgraded from NAV 2016 as well).

**Comment by jswymer** [comment]
Thanks for the feedback! I will try it out, and follow up with my results.

**Comment by jswymer** [comment]
I managed to reproduce your issue on local versions of Dynamics NAV; (however not on W1 version). This is a procedural issue. You should compile objects (without synchronizing) prior to connecting the NAV Server instance. The NAV Server is only required for synchronizing. 

I have updated the article, which will be published soon. Sorry for any problems this has caused and thanks again for filing the issue.
